version: "3.9"  # optional since v1.27.0
services:
  app:
    image: huiping192/video_rtmp_publish
    volumes:
      - ./video:/video
    environment:
      STREAM_URL: rtmp://nginx:1935/stream
      STREAM_KEY: test
  nginx:
    image: alfg/nginx-rtmp
    ports:
      - 1935:1935
      - 8080:80
